### ISSUE TITLE
Question Base de données

### ISSUE THREAD

**Issue by Benoit1462** [CPNV-INFO/Rackakey#2]
Bonjour Monsieur,

J'ai une question concernant l'enregistrement des clés USB dans la base de données. Une clé USB qui vient d'être insérée créée un nouvel enregistrement dans une table, on lui attribue un nom, un hub ainsi qu'un numéro de port, mais du coup cette clé est-elle attribuée à ce port ? Ce que j'aimerais savoir c'est si on change la clé USB de port est-il mis-à-jour ou une erreur est-elle générée ?

Merci d'avance, Meylan Benoit

**Comment by XCarrel** [comment]
Bonjour Benoît,
Tout d'abord, veuillez SVP utiliser le modèle de base de donnée que je viens de pousser sur la branche Master du repository (doc/database/rackakey.mwb)
Ensuite, le fonctionnement recherché est:

- Une clé est insérée dans un port (n'importe lequel) -> On recherche la clé par nom dans la tables usbs -> on ne la trouve pas -> on crée l'enregistrement
- Une clé est insérée dans un port (n'importe lequel) -> On recherche la clé par nom dans la tables usbs -> on la trouve -> on met l'enregistrement à jour (rack_number, port_number)
- Une clé est retirée du port -> on met l'enregistrement à jour: rack_number=NULL, port_number=NULL

**Comment by DardanIljazi** [comment]
Bonjour,

Je viens d'envoyer un mail à Benoît pour trouver un moyen de communication plus rapide dans le cas où il aurait des questions à me poser concernant mon code.

**Comment by Benoit1462** [comment]
merci de votre réponse.
